### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by williamdes** [nijel/upptime-test#1]
Thank you @nijel for making me discover this tool !

Used in https://github.com/wdes/status

https://blog.williamdes.eu/OpenSource/stories/moving-my-uptime-service-to-upptime/

**Comment by nijel** [comment]
We're currently using Cachet for Weblate (https://status.weblate.org/), but it's not maintained anymore and it's time to look for alternatives.

**Comment by williamdes** [comment]
uuptime seems quite good: https://status.datacenters.network/

And the fact that it is server-less is very pleasing !
